server:
  port: 8081
  servlet:
    context-path: /sc-module-demo
spring:
  profiles:
    active: dev
  boot:
    admin:
      client:
        url: http://localhost:8788
        username: admin
        password: admin
# 配置输出日志
logging:
  file:
    path: /Users/dongchuang/Downloads/logs/${spring.application.name}
  level:
    root: INFO
  config: classpath:logback-spring.xml

